birdeye_api_key = "YOUR_BIRDEYE_KEY"
solana_rpc_url = "https://api.mainnet-beta.solana.com"
dex_base_url = "https://dex.example/api"
dex_testnet_url = "https://dex.testnet/api"
metrics_base_url = "https://api.example.com"
discovery_method = "websocket"
stop_loss = 0.1
take_profit = 0.2
