solana_rpc_url = "https://api.mainnet-beta.solana.com"
dex_base_url = "https://quote-api.jup.ag"
agents = [
    "simulation",
]
birdeye_api_key = "dummy"
dex_testnet_url = "https://quote-api.jup.ag"
solana_testnet_rpc_url = "https://api.devnet.solana.com"

[agent_weights]
simulation = 1.0
