solana_rpc_url = "https://api.mainnet-beta.solana.com"
dex_base_url = "https://quote-api.jup.ag"
dex_testnet_url = "https://quote-api.jup.ag"

agents = ["simulation"]

[agent_weights]
simulation = 1.0
