birdeye_api_key = "YOUR_BIRDEYE_KEY"
solana_rpc_url = "https://api.mainnet-beta.solana.com"
dex_base_url = "https://dex.example/api"
dex_testnet_url = "https://dex.testnet/api"
metrics_base_url = "https://api.example.com"
discovery_method = "websocket"
stop_loss = 0.1
take_profit = 0.2
risk_tolerance = 0.1
max_allocation = 0.2
max_risk_per_token = 0.05
trailing_stop = 0.1
max_drawdown = 0.5
volatility_factor = 1.0
