solana_rpc_url = "https://api.mainnet-beta.solana.com/"
dex_base_url = "https://quote-api.jup.ag/"
agents = [
    "simulation",
    "conviction",
    "arbitrage",
    "exit",
    "smart_discovery",
    "trend",
    "momentum",
    "vanta",
    "inferna",
    "portfolio_optimizer",
    "crossdex_rebalancer",
    "mev_sandwich",
    "flashloan_sandwich",
    "sac",
    "artifact_math",
]
birdeye_api_key = "BD1234567890ABCDEFGHIJKL"
dex_testnet_url = "https://quote-api.jup.ag"
orca_api_url = "https://api.orca.so"
raydium_api_url = "https://api.raydium.io"
phoenix_api_url = "https://api.phoenix.trade"
meteora_api_url = "https://api.meteora.ag"
orca_ws_url = ""
raydium_ws_url = ""
jupiter_ws_url = ""
phoenix_ws_url = ""
meteora_ws_url = ""
order_book_ws_url = ""
depth_service = true
depth_max_restarts = 1
compress_events = true
event_compression = "zstd"
use_depth_stream = true
use_depth_feed = false
use_rust_exec = true
use_service_exec = true
use_service_route = true
orca_dex_url = "https://dex.orca.so"
raydium_dex_url = "https://dex.raydium.io"
phoenix_dex_url = "https://dex.phoenix.trade"
meteora_dex_url = "https://dex.meteora.ag"
metrics_base_url = "https://api.coingecko.com/api/v3"
metrics_url = ""
news_feeds = "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml,https://www.coindesk.com/arc/outboundfeeds/rss/"
twitter_feeds = ""
discord_feeds = ""
dex_listing_ws_url = "wss://api.dexscreener.com/latest/dex/ws"
discovery_method = "websocket"
stop_loss = 0.1
take_profit = 0.2
dynamic_weights = true
weight_step = 0.05
use_attention_swarm = false
attention_swarm_model = "attention_swarm.pt"
strategy_selection = true
vote_threshold = 0.1
risk_tolerance = 0.1
max_allocation = 0.2
risk_multiplier = 1.0
max_risk_per_token = 0.05
trailing_stop = 0.1
max_drawdown = 0.5
volatility_factor = 1.0
min_delay = 10
max_delay = 300
cpu_low_threshold = 30.0
cpu_high_threshold = 70.0
max_concurrency = 0
cpu_usage_threshold = 0
concurrency_smoothing = 0.3
concurrency_ki = 0.5
min_rate = 0.01
max_rate = 1.0
depth_freq_low = 1.0
depth_freq_high = 10.0
offline_data_limit_gb = 50
offline_data_interval = 3600
tick_dataset = "solhunter_zero/data/sample_ticks.json"
min_portfolio_value = 20.0
arbitrage_threshold = 0.0
arbitrage_amount = 0.0
use_flash_loans = true
max_flash_amount = 0.02
flash_loan_ratio = 0.1
dex_priorities = "phoenix,meteora,orca,raydium,jupiter"
dex_fees = "{}"
dex_gas = "{}"
dex_latency = "{}"
dex_latency_refresh_interval = 60
use_mev_bundles = true
max_hops = 3
path_algorithm = "graph"
use_gnn_routing = false
gnn_model_path = "route_gnn.pt"
rebalance_interval = 30
slippage_threshold = 0.05
latency_weight = 1.0
fee_weight = 1.0
priority_fees = "0,1,2"
jito_rpc_url = "https://mainnet.block-engine.jito.wtf"
jito_auth = ""
priority_rpc = "https://rpc.ankr.com/solana"
jito_ws_url = ""
jito_ws_auth = ""
event_bus_url = ""
event_bus_peers = []
ws_ping_interval = 20
ws_ping_timeout = 20
broker_url = ""
broker_urls = "redis://localhost:6379"
broker_heartbeat_interval = 30
broker_retry_limit = 3
replicate_trades = false
memory_sync_interval = 5.0
memory_snapshot_path = ""
weights_path = "weights.json"
evolve_interval = 1
mutation_threshold = 0.0
strategy_rotation_interval = 0
weight_config_paths = []
rl_auto_train = false
rl_tune_interval = 3600
regime_weight = 1.0
rl_dynamic_workers = true
rl_prioritized_replay = false
rl_build_mmap_dataset = true
rl_prefetch_buffer = 0
multi_rl = false
rl_population_size = 2
rl_live = false
rl_policy = "mlp"
use_rl_weights = false
rl_weights_path = "rl_weights.json"
rl_weight_population = 4
gpu_memory_index = false
distributed_rl = false
hierarchical_rl = false
hierarchical_model_path = "hier_policy.json"
token_suffix = "bonk"
token_keywords = ""
mempool_score_threshold = 0.0
mempool_stats_window = 5
mempool_threshold = 0.0
depth_threshold = 0.0
bundle_size = 1
volume_threshold = 0
trend_volume_threshold = 0
trend_sentiment_threshold = 0.0

[agent_weights]
simulation = 1.0
conviction = 1.0
arbitrage = 1.0
exit = 1.0
smart_discovery = 1.0
trend = 1.0
momentum = 1.0
vanta = 1.0
inferna = 1.0
portfolio_optimizer = 1.0
crossdex_rebalancer = 1.0
flashloan_sandwich = 1.0
sac = 1.0
mev_sandwich = 1.0
artifact_math = 1.0

[torch]
torch_metal_version = "2.1.0"
torchvision_metal_version = "0.16.0"
