# Default configuration for SolHunter Zero
# Provides sane defaults for both mainnet and testnet networks.

# Mainnet endpoints
solana_rpc_url = "https://api.mainnet-beta.solana.com"
dex_base_url = "https://quote-api.jup.ag"

# Testnet (devnet) endpoints
solana_testnet_rpc_url = "https://api.devnet.solana.com"
dex_testnet_url = "https://quote-api.jup.ag"

# Minimal agent setup
agents = ["simulation"]

[agent_weights]
simulation = 1.0
