name: fullstack-smoke

on:
  workflow_dispatch:
    inputs:
      use_redis:
        description: "Require Redis gate (1/0)"
        default: "0"
      check_ui:
        description: "Poll UI /healthz (1/0)"
        default: "0"
      rl_health_url:
        description: "RL daemon health URL (required)"
        default: "http://127.0.0.1:7070/health"

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Paper-safe env
        run: |
          [ -f .env.example ] && cp .env.example .env || true
          echo "ENV=dev" >> .env
          echo "RISK_MODE=paper" >> .env
          echo "USE_REDIS=${{ github.event.inputs.use_redis }}" >> $GITHUB_ENV
          echo "CHECK_UI_HEALTH=${{ github.event.inputs.check_ui }}" >> $GITHUB_ENV
          echo "RL_HEALTH_URL=${{ github.event.inputs.rl_health_url }}" >> $GITHUB_ENV
      - name: Install package
        run: python -m pip install -e .
      - name: Run smoke
        run: python scripts/smoke_fullstack.py

