name: Runtime Soak (on-demand)
on:
  workflow_dispatch:
    inputs:
      duration_sec:
        description: "Soak duration (seconds)"
        default: "180"
      use_redis:
        description: "Require Redis gate (1/0)"
        default: "0"
      check_ui:
        description: "Poll UI /healthz (1/0)"
        default: "0"
      rl_health_url:
        description: "RL daemon health URL (required)"
        default: "http://127.0.0.1:7070/health"
      ui_health_url:
        description: "UI health URL"
        default: "http://127.0.0.1:3000/healthz"
jobs:
  soak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: python -m pip install -U pip requests
      - name: Paper-safe env
        run: |
          echo "ENV=dev" >> $GITHUB_ENV
          echo "RISK_MODE=paper" >> $GITHUB_ENV
          echo "SELFTEST_SKIP_ARTIFACTS=1" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV
          echo "DURATION_SEC=${{ github.event.inputs.duration_sec }}" >> $GITHUB_ENV
          echo "USE_REDIS=${{ github.event.inputs.use_redis }}" >> $GITHUB_ENV
          echo "CHECK_UI_HEALTH=${{ github.event.inputs.check_ui }}" >> $GITHUB_ENV
          echo "RL_HEALTH_URL=${{ github.event.inputs.rl_health_url }}" >> $GITHUB_ENV
          echo "UI_HEALTH_URL=${{ github.event.inputs.ui_health_url }}" >> $GITHUB_ENV
          echo "SOLANA_RPC_URL=https://api.mainnet-beta.solana.com" >> $GITHUB_ENV
          mkdir -p keypairs && echo "[1,2,3,4]" > keypairs/bot.json
          echo "KEYPAIR_PATH=./keypairs/bot.json" >> $GITHUB_ENV
      - name: Run soak
        run: python scripts/soak_runtime.py
